POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MjM0ODM3MTAsIm1vYmlsZSI6IjE4ODQ0NjQyNTc5IiwiaWQiOjE4MDMzNzIyNzc1MDU1OTMzNDQsImV4cCI6MTcyMzc0MjkxMCwiaWF0IjoxNzIzNDgzNzEwfQ.CiuyE1gbjHr1427Q5NgeRyxpYCB6Ypq8J_ihQRPpNfM

{
  "dailyTrainTicketId":1816757999490961408,
  "date":1721923200000,
  "end":"上海",
  "start":"北京",
  "tickets": [{
    "passengerId":1804427905070141440,
    "passengerIdCard":"123321",
    "passengerName":"test",
    "passengerType":"1",
    "seatTypeCode":"1"
  }],
  "trainCode":"G1"
}

###

GET http://localhost:8000/business/confirm-order/query-line-count/1817427090027450368
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MjM0ODM3MTAsIm1vYmlsZSI6IjE4ODQ0NjQyNTc5IiwiaWQiOjE4MDMzNzIyNzc1MDU1OTMzNDQsImV4cCI6MTcyMzc0MjkxMCwiaWF0IjoxNzIzNDgzNzEwfQ.CiuyE1gbjHr1427Q5NgeRyxpYCB6Ypq8J_ihQRPpNfM
